# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.04.23
_src_path: gh:scientific-python/cookie
backend: hatch
email: nstarman@users.noreply.github.com
full_name: Nathaniel Starkman
license: MIT
org: GalacticDynamics
project_name: zeroth
project_short_description: Efficiently get the index-0 element of an iterable.
url: https://github.com/GalacticDynamics/zeroth
vcs: true
